on:
  push:
    branches:
      - 'master'

name: Run test cases

jobs:
  build:
    name: Run test cases
    runs-on: macos-11
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: brew install eigen
      - run: python -m pip install --upgrade pip
      - run: pip install setuptools attrdict
      - run: pip install wheel pyinstaller regex tatsu wxpython PyMuPDF sympy appdirs cppyy numpy scipy
      - run: sh run_test.sh

